import { Property, Host, Review } from './types';
import { buildGallery } from './images';
import { EXTRA_PROPERTIES } from './extraProperties';

// Replace known-broken Unsplash URLs on legacy core properties with a validated
// cover from their generated gallery.
const BROKEN_CORE_IMAGE: Record<string, string> = {
  'prop-1': 'photo-1583608205776-bfd35f0d9f83',
  'prop-3': 'photo-1513694203232-719a280e022f',
  'prop-5': 'photo-1570129477492-45c003edd2be',
  'prop-6': 'photo-1522708323590-d24dbb6b0267',
};

export const HOST_DATA: Record<string, Host> = {
  yasmine: {
    id: 'host-1',
    name: 'Yasmine El-Fassi',
    avatar: 'https://i.pravatar.cc/150?u=yasmine',
    isSuperhost: true,
    hostingSince: '2019',
    rating: 4.98,
    reviews: 256,
    languages: ['Arabic', 'French', 'English', 'Spanish'],
    responseRate: 98,
    responseTime: 'within an hour',
    properties: ['prop-1', 'prop-7'],
  },
  ahmed: {
    id: 'host-2',
    name: 'Ahmed Benali',
    avatar: 'https://i.pravatar.cc/150?u=ahmed',
    isSuperhost: true,
    hostingSince: '2020',
    rating: 4.95,
    reviews: 189,
    languages: ['Arabic', 'French', 'English'],
    responseRate: 95,
    responseTime: 'within 2 hours',
    properties: ['prop-2'],
  },
  fatima: {
    id: 'host-3',
    name: 'Fatima Zahraoui',
    avatar: 'https://i.pravatar.cc/150?u=fatima',
    isSuperhost: false,
    hostingSince: '2022',
    rating: 4.89,
    reviews: 78,
    languages: ['Arabic', 'French'],
    responseRate: 92,
    responseTime: 'within a few hours',
    properties: ['prop-3'],
  },
  karim: {
    id: 'host-4',
    name: 'Karim Attar',
    avatar: 'https://i.pravatar.cc/150?u=karim',
    isSuperhost: true,
    hostingSince: '2018',
    rating: 4.97,
    reviews: 312,
    languages: ['Arabic', 'English', 'French', 'German'],
    responseRate: 100,
    responseTime: 'within 30 minutes',
    properties: ['prop-4'],
  },
  omar: {
    id: 'host-5',
    name: 'Omar Benjelloun',
    avatar: 'https://i.pravatar.cc/150?u=omar',
    isSuperhost: false,
    hostingSince: '2021',
    rating: 4.85,
    reviews: 134,
    languages: ['Arabic', 'French'],
    responseRate: 88,
    responseTime: 'within a day',
    properties: ['prop-5'],
  },
  nadia: {
    id: 'host-6',
    name: 'Nadia El Mansouri',
    avatar: 'https://i.pravatar.cc/150?u=nadia',
    isSuperhost: true,
    hostingSince: '2020',
    rating: 4.93,
    reviews: 201,
    languages: ['Arabic', 'French', 'English'],
    responseRate: 96,
    responseTime: 'within an hour',
    properties: ['prop-6'],
  },
};

export const AMENITY_ICONS: Record<string, string> = {
  'Wi-Fi': 'Wifi',
  'Pool': 'Pool',
  'Kitchen': 'Kitchen',
  'Parking': 'Parking',
  'Air conditioning': 'Wind',
  'Workspace': 'Monitor',
  'Ocean view': 'Wave',
  'Washing machine': 'Scissors',
  'Washer': 'Scissors',
  'Dryer': 'Scissors',
  'TV': 'Tv',
  'Heating': 'Flame',
  'Coffee maker': 'Coffee',
  'Hair dryer': 'Wind',
  'Iron': 'Scissors',
  'Shampoo': 'Shampoo',
  'Hot tub': 'HotTub',
  'Gym': 'Dumbbell',
  'Essentials': 'Soap',
  'Hangers': 'Scissors',
  'Bed linens': 'BedSingle',
  'Extra pillows and blankets': 'BedDouble',
  'Microwave': 'Microwave',
  'Refrigerator': 'Fridge',
  'Dishwasher': 'Scissors',
  'Smoke detector': 'Smoke',
  'Carbon monoxide detector': 'Smoke',
  'First aid kit': 'Heart',
  'Fire extinguisher': 'Flame',
};

export const AMENITIES_MAP: Record<string, string[]> = {
  'prop-1': ['Wi-Fi', 'Pool', 'Kitchen', 'Parking', 'Air conditioning', 'Workspace', 'Ocean view', 'Washing machine'],
  'prop-2': ['Wi-Fi', 'Kitchen', 'Air conditioning', 'TV', 'Heating', 'Coffee maker', 'Hair dryer', 'Iron'],
  'prop-3': ['Wi-Fi', 'Kitchen', 'Pool', 'Parking', 'Ocean view', 'Washer', 'TV', 'Hangers'],
  'prop-4': ['Wi-Fi', 'Kitchen', 'Parking', 'Air conditioning', 'Workspace', 'Washer', 'Dryer', 'Gym'],
  'prop-5': ['Wi-Fi', 'Kitchen', 'TV', 'Heating', 'Coffee maker', 'Essentials', 'Hangers', 'Bed linens'],
  'prop-6': ['Wi-Fi', 'Pool', 'Kitchen', 'Parking', 'Air conditioning', 'Ocean view', 'Hot tub', 'Washer'],
  'prop-7': ['Wi-Fi', 'Kitchen', 'Parking', 'Air conditioning', 'Workspace', 'TV', 'Washer', 'Fire extinguisher'],
};

const CORE_PROPERTIES: Omit<Property, 'gallery' | 'coverImage'>[] = [
  {
    id: 'prop-1',
    name: 'Ocean View Villa',
    location: 'Essaouira',
    city: 'Essaouira',
    country: 'Morocco',
    lat: 31.5085,
    lng: -9.7595,
    type: 'Villa',
    category: 'Beachfront',
    rating: 4.92,
    reviews: 128,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    price: 180,
    weeklyPrice: 1100,
    monthlyPrice: 3800,
    cleaningFee: 60,
    serviceFee: 85,
    image: 'https://images.unsplash.com/photo-1580587771525-78475757f8c2?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78475757f8c2?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
    ],
    description: 'Experience the pinnacle of Moroccan luxury at this stunning villa along the windswept coast of Essaouira. This architectural masterpiece blends modern minimalist design with traditional Moorish elegance. Wake up to the sound of the Atlantic Ocean, spend your afternoons in our private infinity pool, and dine under the stars in our curated courtyard garden.',
    amenities: AMENITIES_MAP['prop-1'],
    host: HOST_DATA.yasmine,
    isGuestFavorite: true,
    isVerified: true,
    isInstantBook: true,
    cancellationPolicy: 'flexible',
    availableDates: [
      { start: '2026-09-12', end: '2026-09-20' },
      { start: '2026-09-25', end: '2026-10-15' },
      { start: '2026-10-20', end: '2026-11-30' },
    ],
    createdAt: '2024-01-15',
  },
  {
    id: 'prop-2',
    name: 'Desert Oasis Retreat',
    location: 'Merzouga',
    city: 'Merzouga',
    country: 'Morocco',
    lat: 31.0791,
    lng: -4.004,
    type: 'Luxury Camp',
    category: 'Desert',
    rating: 4.85,
    reviews: 84,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    price: 250,
    weeklyPrice: 1500,
    monthlyPrice: 5200,
    cleaningFee: 50,
    serviceFee: 65,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1525143935244-8f371d1b1594?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1470770841072-f978f0fb1975?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&q=80&w=1200',
    ],
    description: 'Escape to the golden dunes of the Sahara in this luxury desert camp. Experience the magic of the Moroccan desert with private tents, gourmet dining under the stars, and camel rides at sunset.',
    amenities: AMENITIES_MAP['prop-2'],
    host: HOST_DATA.ahmed,
    isGuestFavorite: false,
    isVerified: true,
    isInstantBook: false,
    cancellationPolicy: 'moderate',
    availableDates: [
      { start: '2026-10-01', end: '2026-10-31' },
      { start: '2026-11-15', end: '2026-12-20' },
    ],
    createdAt: '2024-02-20',
  },
  {
    id: 'prop-3',
    name: 'Azure Coast Apartment',
    location: 'Tangier',
    city: 'Tangier',
    country: 'Morocco',
    lat: 35.7595,
    lng: -5.834,
    type: 'Apartment',
    category: 'Ocean views',
    rating: 4.78,
    reviews: 56,
    guests: 4,
    bedrooms: 2,
    beds: 3,
    baths: 1,
    price: 120,
    weeklyPrice: 700,
    monthlyPrice: 2400,
    cleaningFee: 40,
    serviceFee: 55,
    image: 'https://images.unsplash.com/photo-1512918728675-ed5a9d970745?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9d970745?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1525408403158-7e5e0c7c5b1d?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=1200',
    ],
    description: 'A stylish apartment in the heart of Tangier with breathtaking views of the Strait of Gibraltar. Perfect for couples or small families looking to explore the white city.',
    amenities: AMENITIES_MAP['prop-3'],
    host: HOST_DATA.fatima,
    isGuestFavorite: true,
    isVerified: true,
    isInstantBook: true,
    cancellationPolicy: 'flexible',
    availableDates: [
      { start: '2026-09-10', end: '2026-10-20' },
      { start: '2026-11-01', end: '2026-12-15' },
    ],
    createdAt: '2024-03-10',
  },
  {
    id: 'prop-4',
    name: 'Mountain Vista Lodge',
    location: 'Ifrane',
    city: 'Ifrane',
    country: 'Morocco',
    lat: 33.5228,
    lng: -5.1104,
    type: 'Cabin',
    category: 'Mountains',
    rating: 4.96,
    reviews: 210,
    guests: 8,
    bedrooms: 4,
    beds: 6,
    baths: 3,
    price: 320,
    weeklyPrice: 1900,
    monthlyPrice: 6800,
    cleaningFee: 80,
    serviceFee: 110,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1470770841072-f978f0fb1975?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=1200',
    ],
    description: 'Cozy mountain lodge nestled in the pine forests of Ifrane, Switzerland of Morocco. Perfect for family retreats with a spacious garden, fireplace, and panoramic mountain views.',
    amenities: AMENITIES_MAP['prop-4'],
    host: HOST_DATA.karim,
    isGuestFavorite: true,
    isVerified: true,
    isInstantBook: true,
    cancellationPolicy: 'strict',
    availableDates: [
      { start: '2026-09-15', end: '2026-10-30' },
      { start: '2026-11-20', end: '2026-12-28' },
    ],
    createdAt: '2024-01-05',
  },
  {
    id: 'prop-5',
    name: 'Chefchaouen Blue Gem',
    location: 'Chefchaouen',
    city: 'Chefchaouen',
    country: 'Morocco',
    lat: 35.1688,
    lng: -5.2636,
    type: 'Riad',
    category: 'Historic homes',
    rating: 4.88,
    reviews: 142,
    guests: 5,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    price: 95,
    weeklyPrice: 550,
    monthlyPrice: 1900,
    cleaningFee: 35,
    serviceFee: 45,
    image: 'https://images.unsplash.com/photo-1539367628448-47557675d776?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1539367628448-47557675d776?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1513406928902-3d9c9a6e7a66?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1559839706-99bc82e9f0d7?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1590001158193-7ef69568623b?auto=format&fit=crop&q=80&w=1200',
    ],
    description: 'A traditional blue riad in the heart of the blue city. Wander through intricate tilework, relax on the rooftop terrace, and soak in the unique charm of Chefchaouen.',
    amenities: AMENITIES_MAP['prop-5'],
    host: HOST_DATA.omar,
    isGuestFavorite: false,
    isVerified: true,
    isInstantBook: false,
    cancellationPolicy: 'flexible',
    availableDates: [
      { start: '2026-09-01', end: '2026-10-15' },
      { start: '2026-11-01', end: '2026-12-20' },
    ],
    createdAt: '2024-04-12',
  },
  {
    id: 'prop-6',
    name: 'Imperial Palace Suite',
    location: 'Marrakech',
    city: 'Marrakech',
    country: 'Morocco',
    lat: 31.6295,
    lng: -7.9811,
    type: 'Luxury Suite',
    category: 'Luxury',
    rating: 4.99,
    reviews: 312,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    price: 550,
    weeklyPrice: 3200,
    monthlyPrice: 11000,
    cleaningFee: 100,
    serviceFee: 150,
    image: 'https://images.unsplash.com/photo-1542314831-068cd1ef6ec7?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1ef6ec7?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1580587771525-78475757f8c2?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1595526114035-2d8391719e4c?auto=format&fit=crop&q=80&w=1200',
    ],
    description: 'Luxuriate in this palatial suite in the heart of Marrakech. Featuring hand-carved marble, a private rooftop terrace with views of the Koutoubia Mosque, and a private butler service.',
    amenities: AMENITIES_MAP['prop-6'],
    host: HOST_DATA.nadia,
    isGuestFavorite: true,
    isVerified: true,
    isInstantBook: true,
    cancellationPolicy: 'strict',
    availableDates: [
      { start: '2026-09-05', end: '2026-09-30' },
      { start: '2026-10-10', end: '2026-11-15' },
    ],
    createdAt: '2024-02-28',
  },
];

// Upgrade legacy core properties with full galleries and repair broken covers.
// The core properties keep their hand-crafted data; only media is generated.
const upgradedCore: Property[] = CORE_PROPERTIES.map((p, i) => {
  const gallery = buildGallery(p.type, i + 1);
  const cover = gallery.find((g) => g.isCover) || gallery[0];
  const hadBroken = BROKEN_CORE_IMAGE[p.id];
  const image = hadBroken ? cover.url : p.image;
  const images = hadBroken ? gallery.map((g) => g.url) : [...p.images, ...gallery.slice(p.images.length).map((g) => g.url)];
  return { ...p, gallery, coverImage: cover.url, image, images };
});

export const MOCK_PROPERTIES: Property[] = [...upgradedCore, ...EXTRA_PROPERTIES];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'review-1',
    propertyId: 'prop-1',
    userId: 'user-1',
    userName: 'Sarah Miller',
    userAvatar: 'https://i.pravatar.cc/150?u=sarah',
    rating: 5,
    cleanliness: 5,
    accuracy: 5,
    communication: 5,
    location: 5,
    checkIn: 5,
    value: 4,
    comment: 'Absolutely stunning villa! The ocean view was breathtaking and the host was incredibly attentive. We would come back in a heartbeat.',
    date: '2026-08-15',
    verified: true,
  },
  {
    id: 'review-2',
    propertyId: 'prop-1',
    userId: 'user-2',
    userName: 'James Chen',
    userAvatar: 'https://i.pravatar.cc/150?u=james',
    rating: 5,
    cleanliness: 5,
    accuracy: 4,
    communication: 5,
    location: 5,
    checkIn: 5,
    value: 5,
    comment: 'Perfect for our family reunion. The infinity pool was amazing and the location could not be better.',
    date: '2026-07-22',
    verified: true,
  },
  {
    id: 'review-3',
    propertyId: 'prop-6',
    userId: 'user-3',
    userName: 'Emma Wilson',
    userAvatar: 'https://i.pravatar.cc/150?u=emma',
    rating: 5,
    cleanliness: 5,
    accuracy: 5,
    communication: 5,
    location: 5,
    checkIn: 5,
    value: 5,
    comment: 'The most luxurious stay we have ever had. The rooftop terrace overlooking the Medina is unforgettable.',
    date: '2026-08-01',
    verified: true,
  },
  {
    id: 'review-4',
    propertyId: 'prop-3',
    userId: 'user-4',
    userName: 'Liam Brown',
    userAvatar: 'https://i.pravatar.cc/150?u=liam',
    rating: 4,
    cleanliness: 4,
    accuracy: 4,
    communication: 4,
    location: 5,
    checkIn: 4,
    value: 4,
    comment: 'Great location with amazing views. A bit small for 4 people but perfect for a couple or small family.',
    date: '2026-07-10',
    verified: true,
  },
];

export const MOCK_CONVERSATIONS = [
  {
    id: 'conv-1',
    propertyId: 'prop-1',
    propertyName: 'Ocean View Villa',
    hostId: 'host-1',
    hostName: 'Yasmine El-Fassi',
    hostAvatar: 'https://i.pravatar.cc/150?u=yasmine',
    messages: [
      { id: 'm1', conversationId: 'conv-1', senderId: 'host-1', senderName: 'Yasmine', senderAvatar: 'https://i.pravatar.cc/150?u=yasmine', content: 'Hello! Welcome to our beautiful villa. I hope you have a wonderful stay! 🌊', timestamp: '2026-09-10T10:00:00Z', read: true },
      { id: 'm2', conversationId: 'conv-1', senderId: 'user-me', senderName: 'You', senderAvatar: 'https://i.pravatar.cc/150?u=me', content: 'Hi Yasmine! Thank you so much! The villa is absolutely stunning. Is the pool heated?', timestamp: '2026-09-10T10:15:00Z', read: true },
      { id: 'm3', conversationId: 'conv-1', senderId: 'host-1', senderName: 'Yasmine', senderAvatar: 'https://i.pravatar.cc/150?u=yasmine', content: 'Yes, it is heated year-round! You are going to love it 😊', timestamp: '2026-09-10T11:00:00Z', read: true },
    ],
    updatedAt: '2026-09-10T11:00:00Z',
  },
];
